spring:
  kafka:
    consumer:
      group-id: camunda-receiver
      auto-offset-reset: earliest
    # change this property if you are using your own
    # Kafka cluster or your Docker IP is different
#    bootstrap-servers: kafka:9092
    bootstrap-servers: localhost:9092
#    bootstrap-servers: 192.168.246.30:29092

tpd:
  topic-name: advice-topic
  messages-per-request: 10


server.port: 8081

camunda:
  endpoint: http://localhost:8080/startEvent
